spring:
  application:
    name: price-service
  profiles:
    active: local
  cloud:
    config:
      uri: http://localhost:8762
      fail-fast: true
      retry:
        max-attempts: 20
        max-interval: 15000
        initial-interval: 10000